spring:
  application:
    name: SpecDoctor-BE

  datasource:
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: false
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            scope: ${SCOPE}

jwt:
  secret_key: ${JWT_SECRET}

app:
  server:
    url: ${APP_SERVER_URL}
  service:
    url: ${APP_CLIENT_URL}
