spring:
  application:
    name: SpecDoctor-BE

  datasource:
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: false
    open-in-view: false

jwt:
  secret: { JWT_SECRET }
  issuer: { JWT_ISSUER }
  token:
    expire: { JWT_TOKEN_EXPIRE }
  refresh:
    expire: { JWT_REFRESH_EXPIRE }
